/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.core.examples;

import org.junit.Test;
import static org.junit.Assert.*;

public class ApplicationTest {
  
  @Test
  public void testAppHasAGreeting() {
    ApplicationMainClass classUnderTest = new ApplicationMainClass();
    assertNotNull("app should have a greeting", classUnderTest.getGreeting());
  }
}
