/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.core.examples;

public class ApplicationMainClass {
    
  public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new ApplicationMainClass().getGreeting());
    }
}
