/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.core.examples.db.layer.jdbc;

import java.util.List;
import java.util.Random;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class MainClass {
  public String getGreeting() {
    return "Hello world.";
  }

  public static void main(String[] args) {
    ClassPathXmlApplicationContext context =
        new ClassPathXmlApplicationContext("db\\jdbc\\BeanConfiguration.xml");

    // Simple with prepare statements and getConnection from datasource object
    // EmployeeDAO employeeDAO = context.getBean("employeeDAO", EmployeeDAO.class);

    //
    EmployeeDAO employeeDAO = context.getBean("employeeDAOTemplate", EmployeeDAO.class);

    // Run some tests for JDBC CRUD operations
    Employee emp = new Employee();
    int rand = new Random().nextInt(1000);
    emp.setId(rand);
    emp.setName("Pankaj");
    emp.setRole("Java Developer");

    // Create
    employeeDAO.save(emp);

    // Read
    Employee emp1 = employeeDAO.getById(rand);
    System.out.println("Employee Retrieved::" + emp1);

    // Update
    emp.setRole("CEO");
    employeeDAO.update(emp);

    // Get All
    List<Employee> empList = employeeDAO.getAll();
    System.out.println(empList);

    // Delete
    employeeDAO.deleteById(rand);

    // Close Spring Context
    context.close();
  }
}
